apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-argo-rollouts
spec:
  project: default
  source:
    chart: argo-rollouts
    helm:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: v2.40.5
    helm:
      releaseName: argo-rollouts
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-rollouts