apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: nodejs-dummy
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-secret"
    gitConfig:
      repository: "https://github.com/robbasualto/Argo.git"
      branch: "main"
      writeBackTarget: "helmvalues:/values/Templates/nodejs-dummy/values.yaml"
  applicationRefs:
    - namePattern: "app-nodejs-dummy"
      images:
        - alias: "nodejs-dummy"
          imageName: "us-east4-docker.pkg.dev/poc-241224/poc/nodejs-dummy:test-1773111108"
          commonUpdateSettings:
            updateStrategy: "name"
            allowTags: "regexp:^test-[0-9]+$"
            pullSecret: "pullsecret:argocd/gar-pullsecret"
          manifestTargets:
            helm:
              tag: "image.tag"
